abstract class AppStates{}
class appinitialstate extends AppStates{}
class Loading_Getuser_state extends AppStates{}
class succsess_Getuser_state extends AppStates{}
class ChangeBootomNav_state extends AppStates{}
class succsess_Pickimage_state extends AppStates{}
class succsess_Pickcoverimage_state extends AppStates{}
class succsess_Upoladcoverimage_state extends AppStates{}
class succsess_Upoladprofileimage_state extends AppStates{}
class succsess_Upoladdata_state extends AppStates{}
class succsess_Pickpostimage_state extends AppStates{}
class succsess_Createpost_state extends AppStates{}
class Loading_Createpost_state extends AppStates{}
class succsess_Upoladpostimage_state extends AppStates{}
class Loading_Upoladpostimage_state extends AppStates{}
class Remove_Postimage_state extends AppStates{}
class succsess_getposts_state extends AppStates{}
class Loading_getposts_state extends AppStates{}
class succsess_likepost_state extends AppStates{}
class succsess_getAllusers_state extends AppStates{}
class Loading_getAllusers_state extends AppStates{}
class succsess_sendMessage_state extends AppStates{}
class Error_sendMessage_state extends AppStates{}
class succsess_getMessages_state extends AppStates{}
class succsess_addComment_state extends AppStates{}
